kelproject/pykube

pykube/http.py

A configurable API Base location so HTTPClient can be used to also access beta extensions that are under the '/apis/extensions' base to the 'v1beta1' version instead of the '/api' base to the 'v1' version.

updated HTTPClient to allow for configurable API Base location

---

setup.cfg

```pep8``` will ignore ```E501``` which is "line too long (82 > 79 characters)". Other exceptions can be listed in ignore per https://pep8.readthedocs.org/en/latest/intro.html#configuration.
Related to #2

Added setup.cfg for pep8 configuration

---

.gitignore
pykube/config.py
pykube/exceptions.py
test/__init__.py
test/test_config.py
test/test_config.yaml

This PR adds the start of unittesting and is compatible with both Python 2.7 and 3.x. It also includes updates to ```.gitignore``` for python and test related files.
```
$ nosetests -v --with-coverage --cover-package=pykube test/
Verify cluster works as expected. ... ok
Verify clusters works as expected. ... ok
Verify contexts works as expected. ... ok
Test Config instance creation. ... ok
Verify set_current_context works as expected. ... ok
Verify user works as expected. ... ok
Verify users works as expected. ... ok
Name                Stmts   Miss  Cover   Missing
-------------------------------------------------
pykube                  0      0   100%
pykube.config          87     15    83%   134, 143-148, 154-158, 164-169
pykube.exceptions       4      0   100% …
```

Start of unittesting

---

pykube/rolling_updater.py

This pull requests fixes the logging system that was not printing anything if you use pykube standalone without any preivous logging configuration.
Improves the rolling update update method by doing the same checks as kubectl like:
- The selector in the new rc needs to be different than the old rc
- The selector in the new rc needs to be the same as the template labels in the new rc
Without these checks, pykube was getting just a non descriptive HTTP error.
The exception messages are copied from kubectl messages when the error occurs.
I also added info messages when creating and cleaning up rcs simulating what kubectl is doing.

Improving rolling updater and fixing logging

---

pykube/objects.py

From the api you can retrieve the objects and their data is stored in .obj as a dict. That dict doesn't have all the elements, the 'kind' and 'apiVersion' items are missing. In pykube luckily we have the version because it belongs to the object class, but there is no way to get the 'kind' item.
Example, this is the obj dict retrieved from kubernetes through the api:
```python
{u'metadata': 
{u'annotations': 
{u'commit': u'00176a9748726369fa23f1d63ad962194d398101',
u'gitrepo': u'configserver',
u'kubereye-managed': u'true'},
u'creationTimestamp': u'2016-03-04T07:13:21Z',
u'name': u'configserver',
u'namespace': u'main',
u'resourceVersion': u'2558676',
u'selfLink': u'/api/v1/namespaces/main/services/configserver',
u'uid': u'9418d01d-e1d8-11e5-bf0d-44a8424811b9'},
u'spec': {u'clusterIP': …
```

Adding kind attribute to objects

---

pykube/objects.py

In the current state of the k8s API, Jobs can be scaled as pods are, but the mechanism of scaling is different in terms of how the API objects are changed. This doesn't allow Job to inherit from ReplicatedAPIObject or share the same method as scale of the replication controller. Scaling of Jobs on kubernetes currently going through setting the parallelism of the Job object. Follows the same logic as the scale method of replication controller.

Scale method for jobs

---

pykube/http.py

The api was being built wrongly thus the resource Namespace was broken
The api url was, for a 'build' namespace:
https://server.com/api/v1/namespaces/build/namespaces
But the right one is:
https://server.com/api/v1/namespaces/build

Some resources like Namespaces don't have a namespace

---

pykube/http.py

8d29bb7 breaks some setups (e.g where session verify is overwritten by purpose).
This change sends a warning but does not raise.

Send a warning instead of raising an exception

---

pykube/config.py
pykube/http.py
test/test_config.py
test/test_config_default_user.yaml
test/test_httpclient.py

Allows me to query kube-api when there is not auth required.  Do I need to up the version in setup.py or do you manage that separately with your release process? (i'm new to python ecosystem)

Support for unrestricted access to kube-apiservers

---

pykube/objects.py

Very basic tweak with potentially far-reaching consequences. Following specific changes:
- `api_kwargs` now accepts a new kwarg: `operations`. I'm totally not sold yet on that particular name, couldn't come up with anything better and will gladly change it to any cool suggestions from reviewers.
- `collections` kwarg to `api_kwargs` renamed to `obj_list`. I can undo this if it's likely to will affect many users downstream negatively, but I found that variable name a bit too _database_-y and not in line with k8s API's logic (ie. `PodList` etc). I figured I'd try sneaking a renaming in along with the other change.

Support for extending resource api request urls

---

pykube/config.py

Checking if `data` is a file that exists (instead of just checking that it begins with a `/`) will allow for relative paths to files like `certificate-authority` in the kube config instead of forcing everything to be an absolute path.

Update config.py to handle relative paths

---

pykube/http.py

This supports clusters with certificates that have not been signed by a
system trusted authority as per http://kubernetes.io/docs/user-guide/kubeconfig-file/#cluster

feat: support insecure-skip-tls-verify

---

pykube/exceptions.py
pykube/http.py

This is useful for reacting to HTTP errors, e.g. trying a create() and
falling back to update() if a 409 is returned.

Add the HTTP status code to HTTPError

---

pykube/__init__.py
pykube/objects.py

Although the feature is in alpha version is fully functional and the RBAC resources (roles, rolebindings, clusterroles and clusterrolebindings) will be kept for future versions.

Adding support for RBAC resources

---

pykube/http.py
test/test_httpclient.py

FIXES: #65 
Get the GKE auth token from the config map.

Fix gke auth 1.3

---

pykube/config.py
pykube/http.py
pykube/session.py
setup.py
test/test_http.py
test/test_httpclient.py
test/test_session.py

This fixes https://github.com/kelproject/pykube/issues/76 and covers the case when the access-token is missing in kube config file.
The only required thing is the setup of gcloud that will create ~/.config/gcloud/application_default_credentials.json needed to get the user credentials.
This is using the oauth module of 'requests', therefore the session object shares the same interface.

Google Cloud oauth authentication

---

README.rst
pykube/query.py

Add support for `fieldSelector` queries, useful to get list of pods based on their phase:
```
pending_pods = pykube.objects.Pod.objects(api).filter(field_selector={"status.phase": "Pending"})
running_pods = pykube.objects.Pod.objects(api).filter(field_selector={"status.phase": "Running"})
```

Add support for fieldSelector queries

---

CHANGELOG.md
pykube/http.py
setup.py

Requests v2.12 has just been pushed to pypi.
This is the first version that contains urllib3 >= 1.18, which contains the fix https://github.com/shazow/urllib3/issues/258 adding support for IP Subject Alternate Names.
This fixes https://github.com/kelproject/pykube/issues/29 (which though closed, didn't actually have a proper resolution, until the urllib3 fix percolated into requests).

Fix pykube cert handling for Python versions < 3.5

---

pykube/__init__.py
pykube/objects.py

Kubernetes 1.5 came out a few days ago which includes changes to PetSets
Petsets are now called StatefulSets
* are now kind: StatefulSets
* use version: 'apps/v1beta1'
* use endpoint: 'statefulsets'
I just added a new class for StatefulSet and imported it into the package namespace.

Added StatefulSet object to objects, imported into __init__.

---

pykube/query.py

Now it returns None for empty data, previously it returns empty array.
Signed-off-by: Proskurin Kirill <kproskurin@mirantis.com>

Fix for k8s 1.5 API

---

README.rst
pykube/http.py

This allows users of this client library the ability to check the server version and handle use cases such as when the HorizontalPodAutoscaler switched over the [endpoint version](https://github.com/kelproject/pykube/blob/cd5b511474bf8854d122af371681fb1dc467a1b9/pykube/objects.py#L325) from `extensions/v1beta1` to `autoscaling/v1`.

add version property for retrieving API version

---

pykube/config.py
pykube/http.py
pykube/objects.py
pykube/query.py
test/test_config.py
test/test_config.yaml

I would like to implement the behavior of
`kubectl config set-context "$context" --namespace="$namespace"`
@brosner This is not enough due to the way `DEFAULT_NAMESPACE` is used to initialize `ObjectManager` for `NamespacedAPIObject`. Do you have an idea how to solve this?

Namespace from context

---

pykube/objects.py

Adds support for the rollout undo command (reverts a previous Deployment update), with identical behavior to
`kubectl rollout undo deployment xxx`
URL syntax is similar to pod logging, so based this off of the logging implementation.
Usage is `pykube.Deployment(kubeapi, obj).rollout_undo(target_revision)`

Add rollout undo feature support

---

pykube/query.py

In python2 it's possible to pass a `unicode` string as a selector, which doesn't trigger this condition, causing an error. By using `six.string_types` instead of `str` we make sure to test for both kinds of strings.

Test if selector is instance of str in backwards compatible way

---

pykube/objects.py

This method is available on both pods and deployments. No reason we can't have it on RC's as well. I've currently got this method monkey patched on to `pykube.ReplicationController` in my project. Seems to be working well.

Add ready property to replication controller class
